# Generated by Django 2.2.7 on 2019-11-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_squashed_0005_auto_20191110_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
