# Generated by Django 2.2.7 on 2019-12-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipient',
            name='token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
