# Generated by Django 2.2.7 on 2019-11-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_newsletterrecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='note',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
