# Generated by Django 2.2.9 on 2020-01-27 18:34

from django.db import migrations, models


def add_default_language_preference(apps, schema_editor):
    NewsletterRecipient = apps.get_model('account', 'NewsletterRecipient')

    for newsletter_recipient in NewsletterRecipient.objects.all():
        newsletter_recipient.language_preference = 'hr'
        newsletter_recipient.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191207_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipient',
            name='language_preference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(
            code=add_default_language_preference,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
