# Generated by Django 2.2.9 on 2020-02-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_newsletterrecipient_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipient',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('hr', 'Croatian')], default='hr', max_length=10),
        ),
    ]
