# Generated by Django 2.2.9 on 2020-02-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200212_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipient',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('hr', 'Croatian')], max_length=10),
        ),
    ]
