exchange_rate_url = 'http://api.hnb.hr/tecajn/v2?valuta=EUR&valuta=USD&valuta=GBP'

country_name_list = (
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua & Deps',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Central African Rep',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Congo (Democratic Rep)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland (Republic)',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea North',
    'Korea South',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar, Burma',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'St Kitts & Nevis',
    'St Lucia',
    'Saint Vincent & the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome & Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad & Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
)

initial_credit_card_logos = (
    {
        'name': 'Visa',
        'slug': 'visa',
        'ordering': 1,
        'published': True,
    },
    {
        'name': 'Mastercard',
        'slug': 'mastercard',
        'ordering': 2,
        'published': True,
    },
    {
        'name': 'Maestro',
        'slug': 'maestro',
        'ordering': 3,
        'published': True,
    },
    {
        'name': 'Diners Club',
        'slug': 'diners-club',
        'ordering': 4,
        'published': True,
    },
    {
        'name': 'Discover',
        'slug': 'discover',
        'ordering': 5,
        'published': True,
    },
    {
        'name': 'American Express',
        'slug': 'american-express',
        'ordering': 6,
        'published': True,
    },
)

contact_slug = 'contact'
payment_delivery_slug = 'payment-and-delivery'
returns_complaints_slug = 'returns-and-complaints'
general_terms_conditions_slug = 'general-terms-and-conditions'
initial_footer_items = (
    {
        'name': 'Contact',
        'location': '/{}/'.format(contact_slug),
        'ordering': 4,
        'published': True,
    },
    {
        'name': 'Payment and delivery',
        'location': '/{}/'.format(payment_delivery_slug),
        'ordering': 3,
        'published': True,
    },
    {
        'name': 'Returns and complaints',
        'location': '/{}/'.format(returns_complaints_slug),
        'ordering': 2,
        'published': True,
    },
    {
        'name': 'General terms and conditions',
        'location': '/{}/'.format(general_terms_conditions_slug),
        'ordering': 1,
        'published': True,
    },
)

initial_footer_share_links = (
    {
        'name': 'Facebook',
        'ordering': 2,
        'location': 'https://www.facebook.com/TheBrushStash/',
        'external': True,
        'published': True,
    },
    {
        'name': 'Instagram',
        'ordering': 1,
        'location': 'https://www.instagram.com/thebrushstash',
        'external': True,
        'published': True,
    },
)

about_the_story_slug = 'about-the-story'
brush_care_slug = 'brush-care'
initial_navigation_items = (
    {
        'name': 'Shop',
        'location': '/',
        'ordering': 6,
        'published': True,
    },
    {
        'name': 'Brush Care',
        'location': '/{}/'.format(brush_care_slug),
        'ordering': 5,
        'published': True,
    },
    {
        'name': 'About / The Story',
        'location': '/{}/'.format(about_the_story_slug),
        'ordering': 4,
        'published': True,
    },
    {
        'name': 'FAQ',
        'location': '/faq/',
        'ordering': 3,
        'published': True,
    },
    {
        'name': 'Log in',
        'location': 'log-in',
        'ordering': 2,
        'published': True,
    },
    {
        'name': 'Register',
        'location': 'register',
        'ordering': 1,
        'published': True,
    },
)

initial_product_types = (
    {
        'name': 'Brush',
        'slug': 'brush',
    },
)

inital_exchange_rates = (
    {
        'currency': 'GBP',
        'currency_code': '826',
        'state_iso': 'GBR',
        'buying_rate': '8.39528000',
        'middle_rate': '8.42054200',
        'selling_rate': '8.44580400',
        'added_value': '10',
    },
    {
        'currency': 'USD',
        'currency_code': '840',
        'state_iso': 'USA',
        'buying_rate': '6.71698600',
        'middle_rate': '6.73719800',
        'selling_rate': '6.75741000',
        'added_value': '10',
    },
    {
        'currency': 'EUR',
        'currency_code': '978',
        'state_iso': 'EMU',
        'buying_rate': '7.40211900',
        'middle_rate': '7.42439200',
        'selling_rate': '7.44666500',
        'added_value': '10',
    },
)
