# Generated by Django 2.2.6 on 2019-10-15 06:53

from django.db import migrations, models

from thebrushstash.constants import initial_credit_card_secure_logos
from thebrushstash.utils import get_default_link_data


def create_credit_card_secure_logos(apps, schema_editor):
    CreditCardSecureLogo = apps.get_model('thebrushstash', 'CreditCardSecureLogo')

    for credit_card_secure_logo in initial_credit_card_secure_logos:
        CreditCardSecureLogo.objects.get_or_create(
            name=credit_card_secure_logo.get('name'),
            defaults={
                **get_default_link_data(credit_card_secure_logo),  # noqa
                'image': credit_card_secure_logo.get('image'),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardSecureLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('ordering', models.IntegerField(blank=True, default=0)),
                ('external', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('webp_image_url', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(upload_to='credit_card_logos')),
            ],
            options={
                'ordering': ('-ordering',),
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=create_credit_card_secure_logos,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
