# Generated by Django 2.2.7 on 2019-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0001_squashed_0005_auto_20191115_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='name_cro',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
