# Generated by Django 2.2.7 on 2019-11-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardlogo',
            name='logo_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
