# Generated by Django 2.2.7 on 2019-11-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0002_creditcardlogo_logo_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardlogo',
            old_name='logo_path',
            new_name='css_class',
        ),
        migrations.RenameField(
            model_name='footersharelink',
            old_name='logo_path',
            new_name='css_class',
        ),
        migrations.RemoveField(
            model_name='creditcardlogo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='creditcardlogo',
            name='srcsets',
        ),
        migrations.RemoveField(
            model_name='creditcardsecurelogo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='creditcardsecurelogo',
            name='srcsets',
        ),
        migrations.AddField(
            model_name='creditcardsecurelogo',
            name='css_class',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='footeritem',
            name='css_class',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='css_class',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
