# Generated by Django 2.2.7 on 2019-11-20 14:41

from django.db import migrations, models

from thebrushstash.constants import initial_region_data


def add_initial_regions(apps, schema_editor):
    Region = apps.get_model('thebrushstash', 'Region')

    for region_data in initial_region_data:
        Region.objects.get_or_create(
            name=region_data.get('name'),
            defaults={
                'language': region_data.get('language'),
                'currency': region_data.get('currency'),
                'shipping_cost': region_data.get('shipping_cost'),
                'published': region_data.get('published'),
                'ordering': region_data.get('ordering'),
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0002_navigationitem_name_cro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Shipping cost')),
                ('ordering', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ('-ordering',),
            },
        ),
        migrations.RunPython(
            code=add_initial_regions,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
