# Generated by Django 2.2.6 on 2019-10-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0002_creditcardsecurelogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherImage',
        ),
    ]
