# Generated by Django 2.2.7 on 2019-12-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0003_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='footeritem',
            name='name_cro',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='footersharelink',
            name='name_cro',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
