# Generated by Django 2.2.6 on 2019-10-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0003_delete_otherimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardlogo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='creditcardlogo',
            name='webp_image_url',
        ),
        migrations.RemoveField(
            model_name='creditcardsecurelogo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='creditcardsecurelogo',
            name='webp_image_url',
        ),
    ]
