# Generated by Django 2.2.7 on 2019-11-14 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0003_auto_20191113_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q('shop', 'product'), models.Q('shop', 'showcase'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
