# Generated by Django 2.2.7 on 2019-11-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0004_auto_20191114_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='standalone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'shop'), ('model', 'product')), models.Q(('app_label', 'shop'), ('model', 'showcase')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
