# Generated by Django 2.2.6 on 2019-10-19 20:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('thebrushstash', '0004_auto_20191019_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='creditcardlogo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='credit_card_logos'),
        ),
        migrations.AddField(
            model_name='creditcardlogo',
            name='srcsets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcardsecurelogo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='credit_card_logos'),
        ),
        migrations.AddField(
            model_name='creditcardsecurelogo',
            name='srcsets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/%Y/%m/')),
                ('youtube_link', models.CharField(blank=True, max_length=1500)),
                ('ordering', models.IntegerField(blank=True, default=0, help_text='If set to 0, items are ordered by creation date')),
                ('srcsets', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Gallery item',
                'verbose_name_plural': 'Gallery items',
                'ordering': ('-ordering', 'created_at'),
            },
        ),
    ]
