# Generated by Django 2.2.7 on 2019-12-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0005_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
    ]
