# Generated by Django 2.2.6 on 2019-10-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0005_auto_20191019_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='css_class',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
