# Generated by Django 2.2.6 on 2019-10-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0006_navigationitem_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersharelink',
            name='logo_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
