# Generated by Django 2.2.7 on 2019-12-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0006_staticpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpagecontent',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
