# Generated by Django 2.2.7 on 2019-12-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0007_staticpagecontent_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpagecontent',
            options={'verbose_name': 'Static pages content'},
        ),
    ]
