# Generated by Django 2.2.6 on 2019-10-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0007_footersharelink_logo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
