# Generated by Django 2.2.7 on 2019-12-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0008_auto_20191203_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='QandAPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=2000)),
                ('question_cro', models.TextField(max_length=2000)),
                ('answer', models.TextField(max_length=5000)),
                ('answer_cro', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Question and answer pair',
            },
        ),
    ]
