# Generated by Django 2.2.7 on 2019-12-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0011_auto_20191203_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='qandapair',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, help_text='If set to 0, items are ordered by creation date'),
        ),
    ]
