# Generated by Django 2.2.7 on 2019-12-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0012_qandapair_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qandapair',
            options={'ordering': ('-ordering',), 'verbose_name': 'Question and answer pair'},
        ),
    ]
