# Generated by Django 2.2.7 on 2019-12-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0015_auto_20191203_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
