# Generated by Django 2.2.8 on 2019-12-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0016_country_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.AddField(
            model_name='country',
            name='name_cro',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='country',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Shipping cost'),
        ),
    ]
