# Generated by Django 2.2.8 on 2019-12-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0017_auto_20191209_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Shipping cost'),
            preserve_default=False,
        ),
    ]
