# Generated by Django 2.2.8 on 2019-12-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0018_auto_20191220_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='Shipping cost'),
        ),
    ]
