# Generated by Django 2.2.8 on 2019-12-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0019_auto_20191220_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='shipping_cost',
        ),
    ]
