# Generated by Django 3.1.1 on 2020-09-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0020_remove_region_shipping_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpagecontent',
            options={'verbose_name': 'Static page content', 'verbose_name_plural': 'Static pages content'},
        ),
    ]
