# Generated by Django 2.2.5 on 2019-09-21 16:39

from django.db import migrations, models
from django.utils.text import slugify
import django.db.models.deletion
import shop.utils

from shop.constants import country_name_list


def update_country_list(apps, schema_editor):
    Country = apps.get_model('shop', 'Country')

    for country_name in country_name_list:
        country_slug = slugify(country_name)
        Country.objects.get_or_create(slug=country_slug, defaults={
            'name': country_name,
            'slug': country_slug,
        })


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=10)),
                ('currency_code', models.CharField(max_length=10)),
                ('state_iso', models.CharField(max_length=10)),
                ('buying_rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('middle_rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'verbose_name': 'Exchange rate',
                'verbose_name_plural': 'Exchange rates',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('zip_postal', models.CharField(max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Country')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Product type',
                'verbose_name_plural': 'Product types',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('price_hrk', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Price (HRK)')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Auto populates from HRK price on save.', max_digits=14, null=True, verbose_name='Price (USD)')),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Auto populates from HRK price on save.', max_digits=14, null=True, verbose_name='Price (EUR)')),
                ('price_chf', models.DecimalField(blank=True, decimal_places=2, help_text='Auto populates from HRK price on save.', max_digits=14, null=True, verbose_name='Price (CHF)')),
                ('image', models.ImageField(upload_to='%Y/%m/%d/')),
                ('ordering', models.IntegerField(blank=True, default=0)),
                ('published', models.BooleanField(default=False)),
                ('product_type', models.ForeignKey(default=shop.utils.get_default_prodcut_type, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductType')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-ordering',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.RunPython(
            code=update_country_list,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
