# Generated by Django 2.2.6 on 2019-10-13 14:19

from django.db import migrations, models
import django.db.models.deletion
import shop.utils

from thebrushstash.constants import (
    inital_exchange_rates,
    initial_product_types,
)


def add_initial_product_types(apps, schema_editor):
    ProductType = apps.get_model('shop', 'ProductType')

    for product_type in initial_product_types:
        ProductType.objects.get_or_create(
            slug=product_type.get('slug'),
            defaults={
                'name': product_type.get('name'),
                'slug': product_type.get('slug'),
                'description': product_type.get('description', ''),
            }
        )


def add_inital_exchange_rates(apps, schema_editor):
    Country = apps.get_model('shop', 'ExchangeRate')

    for exchange_rate in inital_exchange_rates:
        Country.objects.get_or_create(
            currency_code=exchange_rate.get('currency_code'),
            defaults={
                'currency': exchange_rate.get('currency'),
                'currency_code': exchange_rate.get('currency_code'),
                'state_iso': exchange_rate.get('state_iso'),
                'buying_rate': exchange_rate.get('buying_rate'),
                'middle_rate': exchange_rate.get('middle_rate'),
                'selling_rate': exchange_rate.get('selling_rate'),
                'added_value': exchange_rate.get('added_value'),
            }
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thebrushstash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=10)),
                ('currency_code', models.CharField(max_length=10)),
                ('state_iso', models.CharField(max_length=10)),
                ('buying_rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('middle_rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('added_value', models.DecimalField(decimal_places=2, max_digits=5, help_text='The percentage added when converting from HRK')),
            ],
            options={
                'verbose_name': 'Exchange rate',
                'verbose_name_plural': 'Exchange rates',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('zip_postal', models.CharField(max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thebrushstash.Country')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Product type',
                'verbose_name_plural': 'Product types',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('foreword', models.TextField(max_length=300, blank=True, help_text='Short decription for grid view')),
                ('description', models.TextField(blank=True)),
                ('price_hrk', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Price (HRK)')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Auto populates from HRK when saved', max_digits=14, null=True, verbose_name='Price (USD)')),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Auto populates from HRK when saved', max_digits=14, null=True, verbose_name='Price (EUR)')),
                ('price_gbp', models.DecimalField(blank=True, decimal_places=2, help_text='Auto populates from HRK when saved', max_digits=14, null=True, verbose_name='Price (GBP)')),
                ('image', models.ImageField(upload_to='products/%Y/')),
                ('webp_image_url', models.CharField(max_length=1000, blank=True)),
                ('new', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(blank=True, default=0, help_text='If set to 0, products are ordered by "new", then by "created at"')),
                ('published', models.BooleanField(default=False)),
                ('in_stock', models.IntegerField(default=0)),
                ('product_type', models.ForeignKey(default=shop.utils.get_default_product_type, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductType')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-ordering', '-new', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.RunPython(
            code=add_inital_exchange_rates,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=add_initial_product_types,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
