# Generated by Django 2.2.5 on 2019-09-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='exchangerate',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
