# Generated by Django 2.2.7 on 2019-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='zip_postal',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='state',
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_uin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('on-delivery', 'Pay on delivery'), ('paypal', 'Paypal'), ('credit-card', 'Credit card')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='state_county',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
