# Generated by Django 2.2.5 on 2019-10-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190922_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_chf',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto populates from HRK price on save.', max_digits=14, null=True, verbose_name='Price (GBP)'),
        ),
    ]
