# Generated by Django 2.2.7 on 2019-11-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0001_initial'),
        ('shop', '0003_auto_20191110_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thebrushstash.Country'),
        ),
    ]
