# Generated by Django 2.2.7 on 2019-11-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_invoice_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cart',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash-on-delivery', 'Cash on delivery'), ('paypal', 'Paypal'), ('credit-card', 'Credit card')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=100),
        ),
    ]
