# Generated by Django 2.2.6 on 2019-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191019_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='If left empty, auto populates from name', max_length=500),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(blank=True, help_text='If left empty, auto populates from name', max_length=500),
        ),
    ]
