# Generated by Django 2.2.7 on 2019-11-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191117_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='phone_number',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
