# Generated by Django 2.2.7 on 2019-11-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0004_auto_20191114_2356'),
        ('shop', '0004_invoice_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thebrushstash.GalleryItem'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thebrushstash.GalleryItem'),
        ),
    ]
