# Generated by Django 2.2.6 on 2019-10-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191028_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, help_text='If left empty, auto populates from name', max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Showcase',
                'verbose_name_plural': 'Showcases',
            },
        ),
    ]
