# Generated by Django 2.2.6 on 2019-10-29 20:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Used in the description section', null=True, upload_to='shop/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='product',
            name='srcsets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='foreword',
            field=models.TextField(blank=True, help_text='Short decription', max_length=300),
        ),
    ]
