# Generated by Django 2.2.6 on 2019-11-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0008_auto_20191027_1208'),
        ('shop', '0006_auto_20191029_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Invoice',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
    ]
