# Generated by Django 2.2.7 on 2019-11-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='test_image',
            new_name='image',
        ),
    ]
