# Generated by Django 2.2.7 on 2019-11-14 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191115_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Used in the product description section', null=True, on_delete=django.db.models.deletion.CASCADE, to='thebrushstash.GalleryItem'),
        ),
    ]
