# Generated by Django 2.2.8 on 2019-12-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20191130_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('registration', 'Registration'), ('newsletter', 'Newsletter'), ('purchase', 'Purchase')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=100)),
                ('receiver', models.CharField(max_length=500)),
                ('payment_method', models.CharField(choices=[('cash-on-delivery', 'Cash on delivery'), ('paypal', 'Paypal'), ('credit-card', 'Credit card')], max_length=100)),
                ('content', models.TextField()),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Email audit',
                'verbose_name_plural': 'Email audits',
                'ordering': ('status', '-created_at'),
            },
        ),
    ]
