# Generated by Django 2.2.7 on 2019-11-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20191115_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='srcsets',
        ),
        migrations.RemoveField(
            model_name='showcase',
            name='image',
        ),
    ]
