# Generated by Django 2.2.9 on 2020-02-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='recipient_list',
            field=models.ManyToManyField(blank=True, help_text='Use for testing, if left blank the newsletter will be sent to all recipients.', to='account.NewsletterRecipient'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(blank=True, choices=[('ready', 'Ready'), ('in progress', 'In Progress'), ('finished', 'Finished'), ('failed', 'Failed')], max_length=100),
        ),
    ]
