# Generated by Django 2.2.9 on 2020-02-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200209_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='title_cro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='body_image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter/%Y/%m/'),
        ),
    ]
