# Generated by Django 2.2.10 on 2020-05-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200211_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('expires', models.DateTimeField(blank=True, help_text='The code will become inactive on the set time and date.', null=True)),
                ('single_use', models.BooleanField(default=False, help_text='Check if the code is intended for one use only.')),
                ('auto_apply_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Input to apply the same discount to all products.', max_digits=14, null=True)),
            ],
            options={
                'verbose_name': 'Promo code',
                'verbose_name_plural': 'Promo codes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PromoCodeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PromoCode')),
            ],
            options={
                'verbose_name': 'Promo code for product',
                'verbose_name_plural': 'Promo code for products',
                'unique_together': {('promo_code', 'product')},
            },
        ),
        migrations.AddField(
            model_name='promocode',
            name='product_list',
            field=models.ManyToManyField(blank=True, help_text='If blank, creates a discount template for every product.', through='shop.PromoCodeProduct', to='shop.Product'),
        ),
    ]
