# Generated by Django 2.2.10 on 2020-05-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200527_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.PromoCode'),
        ),
    ]
