# Generated by Django 3.0.8 on 2020-07-30 16:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thebrushstash', '0020_remove_region_shipping_cost'),
        ('shop', '0017_auto_20200530_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bag_dump',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.PromoCode'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thebrushstash.Region'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='resend_purchase_confirmation_email',
            field=models.BooleanField(default=False),
        ),
    ]
