# Generated by Django 3.0.8 on 2020-07-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200730_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='register_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscribe_to_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
