# Generated by Django 3.1 on 2020-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200731_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='installments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
