# Generated by Django 3.1 on 2020-08-08 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_installmentoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='installmentoption',
            name='installment_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
