# Generated by Django 3.1 on 2020-08-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_customuser_accepted_cookies'),
        ('shop', '0021_auto_20200808_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='send',
            field=models.BooleanField(default=False, help_text='Checking will mark the newsletter for sending.'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='recipient_list',
            field=models.ManyToManyField(blank=True, help_text='If left blank the newsletter will be sent to all recipients.', to='account.NewsletterRecipient'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='schedule_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank for "now".', null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('finished', 'Finished'), ('failed', 'Failed')], max_length=100),
        ),
    ]
