# Generated by Django 3.1.2 on 2020-10-19 18:14

from django.db import migrations


def copy_price_to_old_price(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')

    for product in Product.objects.all():
        product.old_price_hrk = product.price_hrk
        product.old_price_usd = product.price_usd
        product.old_price_gbp = product.price_gbp
        product.old_price_eur = product.price_eur
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20201019_1800'),
    ]

    operations = [
        migrations.RunPython(
            code=copy_price_to_old_price,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
