# Generated by Django 3.1.3 on 2020-11-29 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20201019_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='flat_discount',
            field=models.BooleanField(default=False, help_text='Check for single use, flat discount, applied to bag total.'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='flat_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to apply (in HRK), must also check the "Flat discount" checkbox.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='promocode',
            name='used',
            field=models.BooleanField(default=False, help_text='Checked when a customer redeems the code.'),
        ),
    ]
