# Generated by Django 3.1.3 on 2020-12-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20201129_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_installments',
            field=models.BooleanField(default=True),
        ),
    ]
