# Generated by Django 3.1.3 on 2020-12-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_product_allow_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='in_person_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
